#:kivy 2.3.0

<CameraWidget>:
    Camera:
        id: camera
        play: True
        height: root.width
        width: 4 * (root.height / 5)
        center: root.center
        canvas.before:
            PushMatrix
            Rotate:
                angle: -90
                origin: self.center
        canvas.after:
            PopMatrix
    
    Button:
        top: 100
        size: 150, 70
        center_x: root.center_x
        text: "capture"
        on_press: root.capture()